// cmdr-pico-breadboard-kit — a commander app for the GeeekPi Pico Breadboard Kit.
//
// Every peripheral on the board is a commander module (see cmdr.toml), so this
// file contains no driver code at all: it is the *composition* — which screen is
// showing, what a touch means right now, what the buttons and the stick do. The
// modules publish, the app decides.
//
// Screens
//   Status  — hostname, IP, uptime, the last input event. The default.
//   Piano   — the panel becomes eight touch keys; the buzzer plays, the RGB LED
//             follows the key. (The original vendor demo booted to a picture of a
//             piano; this one is an actual instrument.)
//   Splash  — the boot card.
//
// Controls (any screen)
//   touch          Piano: play a key. Status: report the coordinate.
//   stick L/R      previous / next screen
//   stick U/D      backlight brighter / dimmer (Piano: transpose an octave)
//   button 0 / 1   toggle LED 0 / 1, with a click
//   `kit …`        the same things from the shell
#include "commander.h"
#include "commander_modules.h"   // generated by cmdr — run `cmdr module`
#include "secrets.h"
#include "core/CmdArgs.h"
#include "core/WifiHooks.h"

// ── Board state ──────────────────────────────────────────────────────────────
// Filled in by the weak ready-hooks the generated file calls. Anything the app
// hasn't been handed stays null, so a module the user disables costs a null check
// rather than a link error — `cmdr module disable buzzer` and this still builds.
static IDisplay         *g_lcd   = nullptr;
static Gt911Module      *g_touch = nullptr;
static JoystickModule   *g_joy   = nullptr;
static ButtonsModule    *g_btn   = nullptr;
static LedModule        *g_leds  = nullptr;
static BuzzerModule     *g_buzz  = nullptr;
static PicoWs2812Module *g_rgb   = nullptr;

enum Screen { ScreenStatus = 0, ScreenPiano, ScreenSplash, ScreenCount };
static Screen   g_screen   = ScreenSplash;
static uint8_t  g_backlight = 255;
static int      g_octave   = 4;          // piano base octave
static char     g_event[40] = "ready";   // last input event, shown on Status
static uint32_t g_bootMs   = 0;

// The panel is used in portrait (rotation 0) — 320 wide, 480 tall.
static constexpr int kPianoKeys = 8;
static const char *kScale[kPianoKeys] = {"c", "d", "e", "f", "g", "a", "b", "c"};
static const uint16_t kKeyColors[kPianoKeys] = {
    rgb565(220, 60, 60),  rgb565(220, 140, 40), rgb565(210, 200, 50), rgb565(70, 200, 80),
    rgb565(60, 170, 210), rgb565(80, 100, 220), rgb565(150, 70, 210), rgb565(220, 80, 160),
};

// ── Small helpers ────────────────────────────────────────────────────────────
static void setEvent(const char *s) {
    size_t i = 0;
    for (; s[i] && i < sizeof(g_event) - 1; i++) g_event[i] = s[i];
    g_event[i] = '\0';
}

// Colours here are full-scale hues. How bright the LED actually gets is the
// `brightness` setting in cmdr.toml (10 on this board — these chips are searing
// at full power), applied by the module on show(). Don't dim by picking small
// values: that dims twice and makes the LED invisible.
static void rgbSet(uint8_t r, uint8_t g, uint8_t b) {
    if (!g_rgb) return;
    g_rgb->fill(r, g, b);
    g_rgb->show();
}

// Append an unsigned number to a buffer; returns the new length. Kept local for
// the same reason the modules avoid printf — it isn't worth the flash here.
static size_t appendUInt(char *buf, size_t pos, size_t cap, uint32_t v) {
    char tmp[11]; int n = 0;
    if (v == 0) tmp[n++] = '0';
    while (v) { tmp[n++] = (char)('0' + v % 10); v /= 10; }
    while (n && pos < cap - 1) buf[pos++] = tmp[--n];
    buf[pos] = '\0';
    return pos;
}
static size_t appendStr(char *buf, size_t pos, size_t cap, const char *s) {
    while (s && *s && pos < cap - 1) buf[pos++] = *s++;
    buf[pos] = '\0';
    return pos;
}

// ── Screens ──────────────────────────────────────────────────────────────────
static void drawSplash() {
    if (!g_lcd) return;
    g_lcd->fill(color::kBlack);
    g_lcd->fillRect(0, 0, g_lcd->width(), 60, rgb565(20, 60, 120));
    g_lcd->drawText(12, 18, "PICO BREADBOARD KIT", color::kWhite, rgb565(20, 60, 120), 2);
    g_lcd->drawText(12, 80,  "commander", color::kCyan, color::kBlack, 3);
    g_lcd->drawText(12, 120, "RP2350 / Pico 2 W", color::kGrey, color::kBlack, 1);
    g_lcd->drawText(12, 150, "stick left/right to change screen", color::kGrey, color::kBlack, 1);
    g_lcd->drawText(12, 166, "or type 'kit help' on the console", color::kGrey, color::kBlack, 1);
}

static void drawStatusFrame() {
    if (!g_lcd) return;
    g_lcd->fill(color::kBlack);
    g_lcd->fillRect(0, 0, g_lcd->width(), 34, rgb565(20, 60, 120));
    g_lcd->drawText(8, 10, "STATUS", color::kWhite, rgb565(20, 60, 120), 2);
    g_lcd->drawText(8, 56,  "host", color::kGrey, color::kBlack, 1);
    g_lcd->drawText(8, 104, "wifi", color::kGrey, color::kBlack, 1);
    g_lcd->drawText(8, 152, "up",   color::kGrey, color::kBlack, 1);
    g_lcd->drawText(8, 200, "last", color::kGrey, color::kBlack, 1);
}

// Repaints only the value rows, so the 1 Hz refresh doesn't flicker the screen.
static void drawStatusValues() {
    if (!g_lcd || g_screen != ScreenStatus) return;
    const int x = 8, w = g_lcd->width() - 16;

    g_lcd->fillRect(x, 72, w, 16, color::kBlack);
    g_lcd->drawText(x, 72, "cmdr-pico-breadboard-kit", color::kWhite, color::kBlack, 2);

    WifiInfo info{};
    char line[48];
    size_t n = 0;
    if (commander_wifi_status(&info) && info.connected) {
        n = appendStr(line, 0, sizeof(line), info.ip);
    } else {
        n = appendStr(line, 0, sizeof(line), "connecting...");
    }
    line[n] = '\0';
    g_lcd->fillRect(x, 120, w, 16, color::kBlack);
    g_lcd->drawText(x, 120, line, info.connected ? color::kGreen : color::kOrange,
                    color::kBlack, 2);

    uint32_t secs = (uint32_t)(hal_time_us() / 1000000ULL) - g_bootMs / 1000;
    n = 0;
    n = appendUInt(line, n, sizeof(line), secs / 3600);
    n = appendStr(line, n, sizeof(line), "h ");
    n = appendUInt(line, n, sizeof(line), (secs / 60) % 60);
    n = appendStr(line, n, sizeof(line), "m ");
    n = appendUInt(line, n, sizeof(line), secs % 60);
    n = appendStr(line, n, sizeof(line), "s");
    g_lcd->fillRect(x, 168, w, 16, color::kBlack);
    g_lcd->drawText(x, 168, line, color::kWhite, color::kBlack, 2);

    g_lcd->fillRect(x, 216, w, 16, color::kBlack);
    g_lcd->drawText(x, 216, g_event, color::kCyan, color::kBlack, 2);
}

static void drawPiano() {
    if (!g_lcd) return;
    g_lcd->fill(color::kBlack);
    const int keyH = g_lcd->height() / kPianoKeys;
    for (int i = 0; i < kPianoKeys; i++) {
        int y = i * keyH;
        g_lcd->fillRect(0, y, g_lcd->width(), keyH - 2, kKeyColors[i]);
        char label[4];
        label[0] = (char)(kScale[i][0] - 32);          // upper-case note name
        label[1] = (char)('0' + (i == kPianoKeys - 1 ? g_octave + 1 : g_octave));
        label[2] = '\0';
        g_lcd->drawText(10, y + keyH / 2 - 12, label, color::kBlack, kKeyColors[i], 3);
    }
}

static void drawScreen() {
    switch (g_screen) {
        case ScreenStatus: drawStatusFrame(); drawStatusValues(); break;
        case ScreenPiano:  drawPiano();  break;
        default:           drawSplash(); break;
    }
}

static void gotoScreen(Screen s) {
    g_screen = s;
    drawScreen();
}

// ── Input handling ───────────────────────────────────────────────────────────
static void playKey(int key) {
    if (key < 0 || key >= kPianoKeys) return;
    char note[4];
    note[0] = kScale[key][0];
    note[1] = (char)('0' + (key == kPianoKeys - 1 ? g_octave + 1 : g_octave));
    note[2] = '\0';
    if (g_buzz) g_buzz->tone(BuzzerModule::noteToHz(note, 2), 220);
    rgbSet((uint8_t)(kKeyColors[key] >> 8), (uint8_t)(kKeyColors[key] >> 3), (uint8_t)(kKeyColors[key] << 3));

    char msg[24];
    size_t n = appendStr(msg, 0, sizeof(msg), "key ");
    n = appendStr(msg, n, sizeof(msg), note);
    setEvent(msg);
}

static bool g_touchDown = false;    // so a beep is one-per-press, not per-event

static void onTouch(const TouchPoint &p, void *) {
    // Beep on the press EDGE only. The module reports movement as well as
    // press/release, so beeping on every event turns a finger held on the glass
    // into a continuous tone — which is exactly what it did.
    bool wasDown = g_touchDown;
    g_touchDown = p.pressed;
    if (!p.pressed) return;
    bool pressEdge = !wasDown;
    if (g_screen == ScreenPiano && g_lcd) {
        // Re-strike only when the finger lands, or slides to a different key —
        // not on every reported movement within one key.
        int keyH = g_lcd->height() / kPianoKeys;
        int key = p.y / (keyH ? keyH : 1);
        static int lastKey = -1;
        if (pressEdge || key != lastKey) { lastKey = key; playKey(key); }
        return;
    }
    char msg[32];
    size_t n = appendStr(msg, 0, sizeof(msg), "touch ");
    n = appendUInt(msg, n, sizeof(msg), (uint32_t)(p.x < 0 ? 0 : p.x));
    n = appendStr(msg, n, sizeof(msg), ",");
    n = appendUInt(msg, n, sizeof(msg), (uint32_t)(p.y < 0 ? 0 : p.y));
    setEvent(msg);
    drawStatusValues();
    if (pressEdge && g_buzz) g_buzz->tone(1200, 30);
}

static void onJoystick(JoyDir d, void *) {
    switch (d) {
        case JoyDir::Left:
            gotoScreen((Screen)((g_screen + ScreenCount - 1) % ScreenCount));
            setEvent("stick left");
            break;
        case JoyDir::Right:
            gotoScreen((Screen)((g_screen + 1) % ScreenCount));
            setEvent("stick right");
            break;
        case JoyDir::Up:
            if (g_screen == ScreenPiano) {
                if (g_octave < 6) g_octave++;
                drawPiano();
                setEvent("octave up");
            } else {
                g_backlight = (uint8_t)(g_backlight > 205 ? 255 : g_backlight + 50);
                if (g_lcd) g_lcd->backlight(g_backlight);
                setEvent("brighter");
            }
            break;
        case JoyDir::Down:
            if (g_screen == ScreenPiano) {
                if (g_octave > 2) g_octave--;
                drawPiano();
                setEvent("octave down");
            } else {
                g_backlight = (uint8_t)(g_backlight < 55 ? 5 : g_backlight - 50);
                if (g_lcd) g_lcd->backlight(g_backlight);
                setEvent("dimmer");
            }
            break;
        default:
            return;                        // returning to centre isn't an action
    }
    drawStatusValues();
}

static void onButton(uint8_t index, bool down, void *) {
    if (!down) return;
    if (g_leds) g_leds->toggle(index);     // the kit's original behaviour
    if (g_buzz) g_buzz->tone(index == 0 ? 1500 : 1900, 40);
    char msg[24];
    size_t n = appendStr(msg, 0, sizeof(msg), "button ");
    n = appendUInt(msg, n, sizeof(msg), index);
    setEvent(msg);
    drawStatusValues();
}

// ── App module: the `kit` command ────────────────────────────────────────────
class KitModule : public IModule {
public:
    const char *name() const override { return "kit"; }
    void init() override {}
    void registerCommands(CommandRegistry &reg) override {
        reg.registerCommand(CMD(
            "kit", "board demo: status, piano, splash, selftest", I2C_NONE,
            [](const char *args, Writer &out, void *) {
                const char *p = cmdarg::skipSpaces(args);
                if (cmdarg::is(p, "status") || cmdarg::empty(p)) { gotoScreen(ScreenStatus); out.writeln("status screen"); return; }
                if (cmdarg::is(p, "piano"))  { gotoScreen(ScreenPiano);  out.writeln("piano screen"); return; }
                if (cmdarg::is(p, "splash")) { gotoScreen(ScreenSplash); out.writeln("splash screen"); return; }
                if (cmdarg::is(p, "note")) {
                    long k;
                    if (!cmdarg::integer(cmdarg::next(p), k, 0, kPianoKeys - 1)) { out.writeln("kit note <0-7>"); return; }
                    playKey((int)k);
                    out.writeln("played");
                    return;
                }
                if (cmdarg::is(p, "selftest")) {
                    // One command that exercises every peripheral in turn — the
                    // bring-up check to run first when the hardware is on the desk.
                    out.writeln("display...");
                    if (g_lcd) { g_lcd->fill(color::kBlack);
                                 g_lcd->drawText(8, 8, "SELF TEST", color::kWhite, color::kBlack, 3); }
                    out.writeln("leds...");
                    if (g_leds) { g_leds->all(true);  hal_delay_ms(400); g_leds->all(false); }
                    out.writeln("rgb...");
                    rgbSet(255, 0, 0); hal_delay_ms(250);
                    rgbSet(0, 255, 0); hal_delay_ms(250);
                    rgbSet(0, 0, 255); hal_delay_ms(250);
                    rgbSet(0, 0, 0);
                    out.writeln("buzzer...");
                    if (g_buzz) g_buzz->playNamed("boot");
                    out.writeln("now press a button, move the stick, touch the screen");
                    out.writeln("(watch the 'last' row on the status screen)");
                    gotoScreen(ScreenStatus);
                    return;
                }
                out.writeln("kit status | piano | splash | note <0-7> | selftest");
            },
            nullptr));
    }
};
static KitModule g_kit;

// A 1 Hz refresh for the uptime row. It rides the UART task's ticker list via the
// weak app-ticker hook the generated file calls — no extra task, no extra stack.
class KitTicker : public IModule {
public:
    const char *name() const override { return "kit-tick"; }
    void init() override {}
    void registerCommands(CommandRegistry &) override {}
    void tick() override {
        uint64_t now = hal_time_us();
        if (now - _last < 1000000ULL) return;
        _last = now;
        drawStatusValues();
    }
private:
    uint64_t _last = 0;
};
static KitTicker g_ticker;

// ── commander entry points ───────────────────────────────────────────────────
extern "C" CommanderConfig commander_config() {
    CommanderConfig cfg;
    cfg.wifi_ssid     = WIFI_SSID;
    cfg.wifi_password = WIFI_PASSWORD;
    cfg.hostname      = "cmdr-pico-breadboard-kit";
    cfg.uart_baud     = 115200;
    cfg.uart_greeting = "cmdr-pico-breadboard-kit — 'help' for commands, 'kit selftest' to check the board";
    return cfg;
}

extern "C" void commander_setup(CommandRegistry &reg) {
    commander_register_modules(reg);       // cmdr-managed: lcd, touch, joy, btn, led, buzz, wled, wifi, i2c
    reg.registerModule(g_kit);
    g_bootMs = (uint32_t)(hal_time_us() / 1000ULL);
    drawScreen();                          // the splash, once the panel is up
    if (g_buzz) g_buzz->playNamed("boot");
    rgbSet(0, 0, 255);
}

extern "C" void commander_on_app_tickers(UartTransport &uart) {
    uart.addTicker(g_ticker);
}

extern "C" void commander_on_wifi_connected() {
    // The IP only exists once DHCP has answered, so the status screen can't show
    // it at setup time — this is the moment it becomes true.
    setEvent("wifi up");
    if (g_screen == ScreenSplash) gotoScreen(ScreenStatus);
    else                          drawStatusValues();
    rgbSet(0, 255, 0);
}

// ── Module ready-hooks (called by the generated commander_modules.h) ─────────
extern "C" void commander_on_display_ready(IDisplay &d) {
    g_lcd = &d;
    d.backlight(g_backlight);
}
extern "C" void commander_on_touch_ready(Gt911Module &t) {
    g_touch = &t;
    // The touch layer must share the display's rotation or presses land rotated.
    // Both default to 0 (portrait); if you change one, change both — or call
    // `lcd rotate N` and `touch rotate N` together from the shell.
    t.setRotation(0);
    t.onTouch(onTouch);
}
extern "C" void commander_on_joystick_ready(JoystickModule &j) {
    g_joy = &j;
    j.onDirection(onJoystick);
}
extern "C" void commander_on_buttons_ready(ButtonsModule &b) {
    g_btn = &b;
    b.onPress(onButton);
}
extern "C" void commander_on_leds_ready(LedModule &l)        { g_leds = &l; }
extern "C" void commander_on_buzzer_ready(BuzzerModule &b)   { g_buzz = &b; }
extern "C" void commander_on_ws2812_ready(PicoWs2812Module &w) { g_rgb = &w; }
